### PR TITLE
Bump 0.5.19

### PR DESCRIPTION
**Pull request by umireon**

### CODE REVIEW

**Comment by umireon** [comment]
@royshil Can you merge this? I don't have write permission on this repository.

**Comment by royshil** [comment]
@umireon sure - but the build fails...

**Comment by umireon** [comment]
Can you rerun the build?

**Comment by umireon** [comment]
bot, build com.obsproject.Studio.Plugin.Backgroundremoval

**Comment by umireon** [comment]
Oh I could rerun the build

**Comment by umireon** [comment]
bot, build com.obsproject.Studio.Plugin.Backgroundremoval

**Comment by umireon** [comment]
bot, build com.obsproject.Studio.Plugin.BackgroundRemoval

**Comment by umireon** [comment]
bot, build com.obsproject.Studio.Plugin.BackgroundRemoval

**Comment by umireon** [comment]
@royshil It has passed!

**Comment by royshil** [comment]
yes - but the status here on github isn't changing... i can't merge

**Pull request merged**
